### PR TITLE
Updated README.md to add details to instructions

### PR DESCRIPTION
**Pull request by abdullahranginwala**
The plugin used previously as an example was causing errors. I have updated the docs to demonstrate an example with another plugin, and also added further instructions to run the project.

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @abdullahranginwala As discussed on Gitter previously, I am wondering if the `pom.xml` would need to be updated as well as this to work? (Since there was some issue with a plugin before for the `mvn clean install` step?) Also, maybe some descriptions about each steps would be good for other people to generalise to other plugins, with some suggestions on the expected outcomes?

**Comment by abdullahranginwala** [comment]
I'm not sure regarding the necessity of updating the `pom.xml`. While I feel updating `pom.xml` solved the issue for me, I can verify it once by going through the entire process without this particular step. I am onto adding more details for each step and will shortly commit that as well.

**Comment by abdullahranginwala** [comment]
@krisstern I realised `pom.xml` is not required, and I have also implemented the changes you proposed.

**Comment by timja** [comment]
Generally squash and merge is done, I wouldn't bother rewriting history, but a meaningful PR title would be good as that would be used as the squashed message

**Comment by abdullahranginwala** [comment]
@krisstern I've made the changes required and also 'squashed' the three commits into one

**Pull request merged**
