### PR TITLE
Bisecting core to determine cause of OOME

### PR DESCRIPTION
**Pull request by jglick**
See #89. https://github.com/jenkinsci/jenkins/compare/jenkins-2.308...jenkins-2.309 so between https://github.com/jenkinsci/jenkins/commit/f88c67e6f1470ae3daa5a289c8c317d992b5665c and https://github.com/jenkinsci/jenkins/commit/3516369a785a30795a39b36d4665c88dd66fce21

@timja

### CODE REVIEW

**Comment by timja** [comment]
FTR https://github.com/jenkins-infra/backend-extension-indexer/pull/38 will improve the run indexer stage from ~25min to approx 5 minutes.

Which will help with any bisecting

**Comment by timja** [comment]
Oh apparently we don't run on high mem here so not as much saving. Running with 12 threads instead of the 48 that the backend indexer job runs with.

https://github.com/jenkins-infra/pipeline-steps-doc-generator/blob/master/Jenkinsfile#L4

4 CPU's instead of 16 that high mem has.
Needs more results but:

1 = 15min
2 = 20min
3 = 14min

**Comment by timja** [comment]
Looks like you've reproduced the issue in https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/94/commits/9b3006707033718ad54d8a14962706e272451c0b. https://ci.jenkins.io/blue/organizations/jenkins/Infra%2Fpipeline-steps-doc-generator/detail/PR-94/2/pipeline

which is the last commit of 2.309 as far as I can tell

**Comment by jglick** [comment]
Still quite a bit faster I think. Just please do not push anything to `backend-extension-indexer` without notifying me, as I need to restart bisection here to keep things reproducible.

**Comment by timja** [comment]
> Still quite a bit faster I think. Just please do not push anything to `backend-extension-indexer` without notifying me, as I need to restart bisection here to keep things reproducible.

I mis-read the stages, we've actually gone from 20min-25min down to 4-5 minutes.

So actually a huge saving

**Comment by jglick** [comment]
Right. Unfortunately it does not fail cleanly, but is at least printing repeated

```
To-space exhausted
```

messages.

**Comment by jglick** [comment]
@basil it seems https://github.com/jenkinsci/jenkins/pull/5687 is the culprit.

**Pull request closed without merging**
