### PR TITLE
Actually switch to pipeline-metadata-utils 1.1

### PR DESCRIPTION
**Pull request by abayer**
Replaces #3

### CODE REVIEW

**Comment by rtyler** [comment]
Removing code 🎈 🎉 🍰

**Comment by abayer** [comment]
@kwhetstone Welp, see #12 - I think it probably *does* make sense to just keep it all in one library for now after all. Sigh. =)

**Comment by gilesgas** [comment]
Hi @abayer ,
I noticed that the steps reference documentation for the "Pipeline: Input Step" plugin (https://jenkins.io/doc/pipeline/steps/pipeline-input-step/) appears to be pulling in (or generating) content from other plugin's / class's documentation. This page seems to be much longer than what it should be.
Do you think this PR would fix this issue?
Cheers,
Giles.

**Comment by jglick** [comment]
> the steps reference documentation for the "Pipeline: Input Step" plugin (https://jenkins.io/doc/pipeline/steps/pipeline-input-step/) appears to be pulling in (or generating) content from other plugin's / class's documentation. I.e. This page seems to be much longer than what it should be.

No, it just accepts a fairly widely implemented extension point (`ParameterDefinition`) for one of its properties.

**Comment by abayer** [comment]
Closing this sucker, since there's no real point to it with #12 merged.

**Pull request closed without merging**
