### PR TITLE
 chore: start building pipeline with infra.ci.jenkins.io

### PR DESCRIPTION
**Pull request by dduportal**
https://github.com/jenkins-infra/helpdesk/issues/3087

Please note that this only add a build to infra.ci (and does not discard ci.jenkins.io current build) for now so we can A/B test the jenkins.io build.

This PR also gets the latest "zip" fixes from @MarkEWaite

### CODE REVIEW

**Comment by dduportal** [comment]
Blocked by https://github.com/jenkins-infra/helpdesk/issues/3087

**Comment by dduportal** [comment]
Build failing with Java heap space error. 

Makes sense: infra.ci uses T3Medium instances (e.g. 4 Gb) while ci.jenkins.io uses T4XLarge (16Gb).

Gotta update this

**Comment by dduportal** [comment]
Blocked by https://github.com/jenkins-infra/kubernetes-management/pull/3126

**Review by lemeurherve — APPROVED** [review]
LGTM

image

**Pull request merged**
