### PR TITLE
Switch to using org.jenkins-ci.infra:pipeline-metadata-utils:1.0.

### PR DESCRIPTION
**Pull request by abayer**
cc @kwhetstone

### CODE REVIEW

**Comment by kwhetstone** [comment]
I like this, especially if those classes could be used in other cases.  There have been some other changes in the classes, and there's a failure in the PR merge now.  After I fix this other failure that appears to be happening in the job, I think we should close this, add the changes to the metadata-utils classes and cut a new version, then open another PR with the most up to date pieces.  Making changes soon.

**Comment by abayer** [comment]
I'm gonna try to resurrect this to help with INFRA-1053...

**Comment by abayer** [comment]
Replaced by #11

**Comment by kwhetstone** [comment]
Unfortunately this sort of got steamrolled with other changes.  I like having it in a separate class, especially if the underlying "Jenkins-less plugin manager" would be useful for other applications.

**Pull request closed without merging**
