### PR TITLE
Update core to 2.263.3, args4j to 2.33

### PR DESCRIPTION
**Pull request by zbynek**
... and change update the mock code to avoid some exceptions

### CODE REVIEW

**Review by kwhetstone — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I'm not sure why the PR build on ci.jenkins.io runs out of memory and spends 10 hours running, while the master branch completes in 30 minutes or less.  Any insights to offer?

**Review by MarkEWaite — APPROVED** [review]

**Comment by zbynek** [comment]
So the main method checks for `Exception`s with a comment that they have to be explicitly caught and program exited, otherwise the job keeps hanging. I guess if it encounters an `Error` instead (such as out of memory) it's not caught and it keeps hanging (maybe because of the memory monitoring thread that runs in parallel?).

I guess the next step is to try it locally with more plugins than the default ~50 and see if I can reproduce the out of memory.

**Comment by zbynek** [comment]
It turns out that this mock
```
 when(mockJenkins.getRootDir()).thenReturn(new File(System.getProperty("java.io.tmpdir")));
 ```
was the cause of builds running for hours and running out of memory. I originally added it to avoid some warnings in the log, but those are not critical.

**Review by MarkEWaite — APPROVED** [review]
Looks great to me.  Thanks for making the change!

**Comment by MarkEWaite** [comment]
Merging since @kwhetstone had approved the changes previously.

**Pull request merged**
