### PR TITLE
Simplify ProcessAsciiDocTest

### PR DESCRIPTION
**Pull request by JanaganSaravanan**
Replace try/catch sequences in the tests with assertThrows

Replace assertTrue(true) and assertTrue(false) with assertions that state the cause of the failure

### CODE REVIEW

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
Thanks for the pull request.  Much appreciated.  A few points that need more work.

* Please create a working branch for your future pull requests rather than submitting from the branch named `master`.  When you submit a pull request from the branch named `master`, you create unnecessary work for the maintainers of the repository as they review your pull request.  Help maintainers by always creating a new branch for your pull request
* JUnit 4 (used in this repository) does not provide the jupiter API.  That's limited to JUnitt 5.  Before submitting a pull request, be sure that you've compiled the code and confirmed that the tests are still passing.  I fixed that in 52278d0
* JUnit 4 does not require that test methods must start with the word `test`.  Don't rename test methods unless there is a compelling reason to do so.  I fixed that in 52278d0
* There are still multiple cases where `assertTrue(false)` is being used.  It is much better to remove the try / catch completely from those cases and allow the test to fail if an IOException occurs.  JUnit will display a stack trace that helps maintainers identify the cause of the failure.  I'd prefer that you fix that as part of your experience, but let me know if you're not able to do so.  This pull request is already an improvement, even if it does not yet solve all the cases

**Comment by JanaganSaravanan** [comment]
Hi! As a beginner, I really appreciate all the useful information. I am sorry i could not resolve the issue you mentioned. Thank you,

**Comment by MarkEWaite** [comment]
> Hi! As a beginner, I really appreciate all the useful information. I am sorry i could not resolve the issue you mentioned. Thank you,

No problem.  Are you interested in continuing to improve this pull request?

**Review by MarkEWaite — APPROVED** [review]
Thanks for the contribution!

**Comment by JanaganSaravanan** [comment]
No, Thank you for all the work. I could really learn lot from this contribution. Thanks.

**Pull request merged**
